### ISSUE TITLE
Rollup plugins for tests

### ISSUE THREAD

**Issue by arose** [rollup/rollup-starter-project#17]
As far as I can tell the test files for mocha are created on-demand by babel. I have some simple rollup plugins that allow me to import files as strings. However in the tests this does fail. Any suggestions? I would be okay with adding a babel plugin with the same functionality as the rollup plugin. Or, can rollup be used to create the test files for mocha on-demand?

**Comment by eventualbuddha** [comment]
> can rollup be used to create the test files for mocha on-demand?

You can build a bundle using rollup that includes tests, but I've found it's difficult to enable debugging in a meaningful way when doing that. Open to suggestions, though!
