### ISSUE TITLE
external dependencies

### ISSUE THREAD

**Issue by zwhitchcox** [rollup/rollup-starter-project#18]
Can you please add an example with external dependencies? I can't get them to work

**Comment by zwhitchcox** [comment]
And in the meantime if anyone has any links to a project that has already implemented external dependencies, I would be very interested to see it!

**Comment by eventualbuddha** [comment]
When you say "external dependencies", you mean external dependencies that you want to bundle into your dist file? If so, rollup itself does this, as does some of its dependencies like magic-string.
